import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header/Header';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="mt-20 bg-gradient-to-bl from-sky-950 via-gray-950 to-black">
          {children}
        </main>
      </body>
    </html>
  )
}
